version: "3.9"

services:
  database:
    image: postgres
    container_name: database_python_test
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - pgdata:/data/postgres
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
    networks:
      - postgres

  api:
    image: python-study-fastapi:latest
    ports:
      - 80:8000
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - OUTH_SECRET_KEY=${OUTH_SECRET_KEY}
      - OUTH_ALGORITHM=${OUTH_ALGORITHM}
      - OUTH_ACCESS_TOKEN_EXPIRE_MINUTES=${OUTH_ACCESS_TOKEN_EXPIRE_MINUTES}
    #command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    networks:
      - postgres
    depends_on:
      - database

networks:
  postgres:
    driver: bridge

volumes:
  pgdata:
    driver: local
